name: ${project.name}
main: jp.azisaba.lgw.ecplus.EnderChestPlus
version: ${project.version}
author: siloneco
description: ${project.description}
commands:
  enderchestplus:
    usage: /{LABEL} [Player/UUID]
    permission: enderchestplus.command.enderchestplus
    aliases: [ecp]
  receivedropped:
    usage: /{LABEL}
    permission: enderchestplus.command.receivedropped
permissions:
  enderchestplus.command.enderchestplus:
    default: op