name: EnderChestPlus
main: jp.azisaba.lgw.ecplus.EnderChestPlus
version: ${project.version}
author: siloneco
description: ${project.description}
api-version: 1.15
depend:
  - Vault
commands:
  enderchestplus:
    permission: enderchestplus.command.enderchestplus
    aliases: [ ecp ]
  receivedropped:
    usage: /{LABEL}
    permission: enderchestplus.command.receivedropped
  ec2:
    description: Opens the ender chest
    usage: /ec2
permissions:
  enderchestplus.command.enderchestplus:
    default: op
