name: EnderChestPlus
main: jp.azisaba.lgw.ecplus.EnderChestPlus
version: ${project.version}
author: siloneco
description: ${project.description}
api-version: 1.16
commands:
  enderchestplus:
    permission: enderchestplus.command.enderchestplus
    aliases: [ ecp ]
  receivedropped:
    usage: /{LABEL}
    permission: enderchestplus.command.receivedropped
  ec:
    description: Opens the ender chest
    usage: /ec
permissions:
  enderchestplus.command.enderchestplus:
    default: op